### ISSUE TITLE
any chance of supporting btrfs partition?

### ISSUE THREAD

**Issue by codeitlikemiley** [mdaffin/arch-pkgs#10]
Hope you can add support for btfrs 
I think this is a perfect match for  Arch rolling release
You can see it in action with this [VIDEO](https://www.youtube.com/watch?v=TKdZiCTh3EM)

**Comment by mdaffin** [comment]
It is fairly easy to change the file system used simply by adding the btrfs-progs package (either as a dependency to the [main meta package](https://github.com/mdaffin/arch-pkgs/blob/master/pkg/mdaffin/PKGBUILD#L50-L54) or by adding it as an extra package to install ([on line 80](https://github.com/mdaffin/arch-pkgs/blob/master/installer/install-arch#L80)) and changing the installer to format the partition with btrfs ([on line 66](https://github.com/mdaffin/arch-pkgs/blob/master/installer/install-arch#L66)).

However, this repo is not designed for direct general consumption, it contains things specific to my needs and is open more as an example/demo of what is possible. I have no plans to make these packages/scripts generic for everyone's use cases as that would complicate them and make both maintenance and the ability to tweak them for every niche purpose harder. Instead, I encourage you to fork this repo and adjust them to your own needs and requirements.

If you have not already you should read my blog post about [the installer](https://disconnected.systems/blog/archlinux-installer/) and [creating/managing meta-packages](https://disconnected.systems/blog/archlinux-meta-packages/).

If you want some feedback on what you have done or if you are struggling with a particular point or just want more advice then I am more than willing to take a look and help. But I have no intention of making these scripts run time customizable or to meet other use cases that I do not require.

Thanks for your interest and if you do manage it, let me know and I can add links to your scripts as an example for others to follow should they choose to.
