### ISSUE TITLE
rankmirrors now in pacman-contrib

### ISSUE THREAD

**Issue by hobnobpirate** [mdaffin/arch-pkgs#6]
Install script fails because rankmirrors has moved to pacman-contrib.

**Comment by mdaffin** [comment]
Thanks for this, I have updated the script to install pacman-contrib as well as tweaked the rankmirror execution to pull down the latest mirrors from https://www.archlinux.org/mirrorlist and filter on a country code (be sure to update that for your country) as it was being very slow for me with all of the mirrors included.
